version: '3'
services:
  app:
    build:
      context: ./
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - WEBPAGES_LOCATION=/tmp

  celery-worker:
    build:
      context: ./
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    environment:
      - BROKER_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - WEBPAGES_LOCATION=/tmp # The host dir where webpages are saved
    volumes:
      - /tmp:/tmp/webpages

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"